### PR TITLE
Fix SRV format documentation to align with RFC

### PR DESCRIPTION
**Pull request by kl52752**

### CODE REVIEW

**Comment by prameshj** [comment]
/ok-to-test

Thanks! Can you also modify this line - https://github.com/kubernetes/dns/blob/c61bc06b6c1f2296ac937e135b6b7a89a2a73204/docs/specification.md#242---srv-records?

**Comment by kl52752** [comment]
@prameshj  done :)

**Review by chrisohaver — APPROVED** [review]

**Pull request merged**
