### PR TITLE
Bump debian base image to v2.1.2

### PR DESCRIPTION
**Pull request by jonesbr17**
This should resolve https://github.com/kubernetes/dns/issues/386

### CODE REVIEW

**Comment by prameshj** [comment]
/lgtm
/ok-to-test

Would be good to check that the new images startup successfully using:
```
./image-checks.sh <image-tag> <registry-name>
```

**Comment by prameshj** [comment]
Build passed - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/dns-push-images/1298323430826840066

I tried `./image-checks.sh v20200825-1.15.13-10-gcac6070 gcr.io/k8s-staging-dns/` and it works.

**Comment by prameshj** [comment]
> Hi @prameshj are there plans for a patch release soon?

Yes, i am planning to make one today.

**Comment by rtheis** [comment]
@prameshj Thank you.  Given the move to `us.gcr.io/k8s-artifacts-prod`, where do we find the new image for https://github.com/kubernetes/dns/releases/tag/1.15.14?

**Comment by prameshj** [comment]
The new automated build is not triggering for new tags, it only seems to work for new commits. I submitted https://github.com/kubernetes/test-infra/pull/19254 to fix it and pushed a test tag, but I don't see the image building.
We should see images with the new tag in gcr.io/k8s-staging-dns which can then be promoted.

**Comment by prameshj** [comment]
Images can be found in "k8s.gcr.io/dns/k8s-dns-node-cache:1.15.14", "k8s.gcr.io/dns/k8s-dns-kube-dns:1.15.14"...

**Pull request merged**
