### PR TITLE
reduce binary size

### PR DESCRIPTION
**Pull request by oilbeater**
remove symbol tables and debug info to reduce binary size, see https://golang.org/cmd/link/

### CODE REVIEW

**Comment by bowei** [comment]
What is the reduction? Give original size and new size...I'm not sure if this is really necessary.

**Comment by oilbeater** [comment]
dnsmasq-nanny 35M -> 22M
kube-dns 44M-> 28M
sidecar 36M -> 23M

We are trying to build our Kubernetes distribution, and the size is really matter because network condition is not so good everywhere, we want to minimize the network transfer time.

**Comment by thockin** [comment]
Note that if you do this, any stack-dump is going to be missing symbols.  I
don't think we should do this for the upstream binaries.

**Comment by oilbeater** [comment]
@thockin these flags only strip symbols for debugger, other information like panic stack trace still kept

**Pull request closed without merging**
