### PR TITLE
Update modules

### PR DESCRIPTION
**Pull request by SuperQ**
* Update CoreDNS to 1.8.3.
* Update Kubernetes to 1.19.x
* Fix up CoreDNS package code.
* Fix up deprecated/moved Kuberntes package code.
* Cleanup excess indirect dependencies.
* Upgrade to Go 1.16.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
I've split the massive `vendor` dir update into a separate commit so it's easier to review.

**Comment by prameshj** [comment]
Thanks for doing this!

Are changes in https://github.com/kubernetes/dns/pull/455/commits/bab4491076618a19c3bb89f35f97e11745a13407 the only manual changes?

I assume the vendor changes were auto-generated by `go mod vendor`, right?

Is kubernetes 1.21 changed needed in order to use coreDNS 1.8.3?

**Comment by SuperQ** [comment]
Yes, the first commit is the manual-ish (lots of `go get FOO`). The second commit is just automatic `go mod vendor`.

I didn't specifically try and get a minimal upgrades. I was trying to update a majority of the components.

**Comment by SuperQ** [comment]
Oops, I missed one file in the commit to update the build to Go 1.16.

**Comment by SuperQ** [comment]
Ok, I fixed up a couple of build bugs, and rolled back Kubernetes 1.19, so we match the currently supported oldest version.

**Comment by prameshj** [comment]
Thanks!

I am not sure why there isn't a travis build running for this PR - https://travis-ci.org/github/kubernetes/dns/pull_requests

**Comment by SuperQ** [comment]
`travis-ci.org` is shut down. You need to convert to `travis-ci.com`. See [this documentation](https://docs.travis-ci.com/user/migrate/open-source-repository-migration).

**Comment by prameshj** [comment]
> `travis-ci.org` is shut down. You need to convert to `travis-ci.com`. See [this documentation](https://docs.travis-ci.com/user/migrate/open-source-repository-migration).

Thanks! Looks like most kubernetes/* repos have moved off of travis. I will migrate the travis build steps to the prow config in https://github.com/kubernetes/test-infra/blob/3f7f4dec23d30d0c6c8891c91af29c9097222c10/config/jobs/kubernetes/sig-network/sig-network-misc.yaml#L183 and we can retry it on this PR.

**Comment by Shahard2** [comment]
Any news? 

Please merge this ASAP!! :)

**Comment by prameshj** [comment]
> Any news?
> 
> Please merge this ASAP!! :)

I am going to try out the updated prow config in https://github.com/kubernetes/test-infra/pull/22646 on this PR. Since this is a large change, I would like to merge it after all our presubmits pass.

Also, note that this upgraded k8s dependency to 1.19.

**Comment by SuperQ** [comment]
Looks like prow failed:

```
execute.py: error: unrecognized arguments: -c make build
```

**Comment by prameshj** [comment]
> Looks like prow failed:
> 
> ```
> execute.py: error: unrecognized arguments: -c make build
> ```

Yes, simplifying it in https://github.com/kubernetes/test-infra/pull/22646

**Comment by SuperQ** [comment]
It looks like docker-in-docker isn't working:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by prameshj** [comment]
I will cut a tag 1.18.1. to pick up vulnerability fixes in https://github.com/kubernetes/dns/pull/456

This PR will be included in 1.19.0 image.

**Comment by prameshj** [comment]
@SuperQ would you be able to run ./images-check.sh to make sure that all the images built with these changes can startup correctly?

**Comment by SuperQ** [comment]
I'm not sure how the script is supposed to work. I tried this:

```
$ make clean
$ make build
$ make test
$ make all-containers
$ ./image-checks.sh 1.18.0-2-g9a7f627
```

Everything works, but I'm getting these errors:

```
Verifying that iptables exists in node-cache image
Unable to find image 'gcr.io/google-containers/k8s-dns-node-cache:1.18.0-2-g9a7f627' locally
docker: Error response from daemon: manifest for gcr.io/google-containers/k8s-dns-node-cache:1.18.0-2-g9a7f627 not found: manifest unknown: Failed to fetch "1.18.0-2-g9a7f627" from request "/v2/google-containers/k8s-dns-node-cache/manifests/1.18.0-2-g9a7f627".
See 'docker run --help'.
Verifying that node-cache binary exists in node-cache image
Unable to find image 'gcr.io/google-containers/k8s-dns-node-cache:1.18.0-2-g9a7f627' locally
docker: Error response from daemon: manifest for gcr.io/google-containers/k8s-dns-node-cache:1.18.0-2-g9a7f627 not found: manifest unknown: Failed to fetch "1.18.0-2-g9a7f627" from request "/v2/google-containers/k8s-dns-node-cache/manifests/1.18.0-2-g9a7f627".
See 'docker run --help'.
Verifying dnsmasq-nanny startup
Unable to find image 'gcr.io/google-containers/k8s-dns-dnsmasq-nanny:1.18.0-2-g9a7f627' locally
docker: Error response from daemon: manifest for gcr.io/google-containers/k8s-dns-dnsmasq-nanny:1.18.0-2-g9a7f627 not found: manifest unknown: Failed to fetch "1.18.0-2-g9a7f627" from request "/v2/google-containers/k8s-dns-dnsmasq-nanny/manifests/1.18.0-2-g9a7f627".
See 'docker run --help'.
Verifying kube-dns startup
Unable to find image 'gcr.io/google-containers/k8s-dns-kube-dns:1.18.0-2-g9a7f627' locally
docker: Error response from daemon: manifest for gcr.io/google-containers/k8s-dns-kube-dns:1.18.0-2-g9a7f627 not found: manifest unknown: Failed to fetch "1.18.0-2-g9a7f627" from request "/v2/google-containers/k8s-dns-kube-dns/manifests/1.18.0-2-g9a7f627".
See 'docker run --help'.
Verifying sidecar startup
Unable to find image 'gcr.io/google-containers/k8s-dns-sidecar:1.18.0-2-g9a7f627' locally
docker: Error response from daemon: manifest for gcr.io/google-containers/k8s-dns-sidecar:1.18.0-2-g9a7f627 not found: manifest unknown: Failed to fetch "1.18.0-2-g9a7f627" from request "/v2/google-containers/k8s-dns-sidecar/manifests/1.18.0-2-g9a7f627".
See 'docker run --help'.
```

It seems like the container tagging isn't right.

**Comment by prameshj** [comment]
> 1.18.0-2-g9a7f627

Where did you get this tag from? If it is from the presubmit job logs, that does not currently push the images to any registry, for each PR. You would need to push to a test repo to verify this.

**Comment by SuperQ** [comment]
That image tag gets generated when I build the containers locally.

```
gcr.io/k8s-staging-dns/k8s-dns-sidecar-s390x           1.18.0-2-g9a7f627   65f3a2119bdb   8 hours ago    99.4MB
gcr.io/k8s-staging-dns/k8s-dns-node-cache-s390x        1.18.0-2-g9a7f627   b0455e75a12a   8 hours ago    130MB
gcr.io/k8s-staging-dns/k8s-dns-kube-dns-s390x          1.18.0-2-g9a7f627   3e5ea8666e6e   8 hours ago    104MB
gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-nanny-s390x     1.18.0-2-g9a7f627   60023960ddf6   8 hours ago    99.9MB
gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-s390x           1.18.0-2-g9a7f627   c21902f64cfa   8 hours ago    64.7MB
gcr.io/k8s-staging-dns/k8s-dns-sidecar-ppc64le         1.18.0-2-g9a7f627   596057683415   8 hours ago    130MB
gcr.io/k8s-staging-dns/k8s-dns-node-cache-ppc64le      1.18.0-2-g9a7f627   2b71ff6f6ab8   9 hours ago    170MB
gcr.io/k8s-staging-dns/k8s-dns-kube-dns-ppc64le        1.18.0-2-g9a7f627   16a372d31c0c   9 hours ago    135MB
gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-nanny-ppc64le   1.18.0-2-g9a7f627   484a1e56577e   9 hours ago    132MB
gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-ppc64le         1.18.0-2-g9a7f627   562ef739802a   9 hours ago    98.1MB
gcr.io/k8s-staging-dns/k8s-dns-sidecar-arm64           1.18.0-2-g9a7f627   522baa208f5c   9 hours ago    95.9MB
gcr.io/k8s-staging-dns/k8s-dns-node-cache-arm64        1.18.0-2-g9a7f627   b6db6d895fc6   9 hours ago    127MB
gcr.io/k8s-staging-dns/k8s-dns-kube-dns-arm64          1.18.0-2-g9a7f627   84e00ced7bab   9 hours ago    100MB
gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-nanny-arm64     1.18.0-2-g9a7f627   21b5c64ed3e5   9 hours ago    96.8MB
gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-arm64           1.18.0-2-g9a7f627   094e6ea85fc1   9 hours ago    63.4MB
gcr.io/k8s-staging-dns/k8s-dns-sidecar-arm             1.18.0-2-g9a7f627   35662a9929d5   9 hours ago    80.7MB
gcr.io/k8s-staging-dns/k8s-dns-node-cache-arm          1.18.0-2-g9a7f627   83674b94c08b   9 hours ago    109MB
gcr.io/k8s-staging-dns/k8s-dns-kube-dns-arm            1.18.0-2-g9a7f627   8bfa3f02abae   9 hours ago    84.7MB
gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-nanny-arm       1.18.0-2-g9a7f627   97499943354a   9 hours ago    81.6MB
gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-arm             1.18.0-2-g9a7f627   df341d688dff   9 hours ago    50.7MB
gcr.io/k8s-staging-dns/k8s-dns-sidecar-amd64           1.18.0-2-g9a7f627   05831272d3e4   9 hours ago    98.9MB
gcr.io/k8s-staging-dns/k8s-dns-node-cache-amd64        1.18.0-2-g9a7f627   40a2efa1b56e   9 hours ago    132MB
gcr.io/k8s-staging-dns/k8s-dns-kube-dns-amd64          1.18.0-2-g9a7f627   104979994100   9 hours ago    104MB
gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-nanny-amd64     1.18.0-2-g9a7f627   4569d6b68cc0   9 hours ago    96.8MB
gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-amd64           1.18.0-2-g9a7f627   eec3f1e0ba1f   9 hours ago    61.2MB
```

**Comment by prameshj** [comment]
Got it, then you just need to run `/image-checks.sh 1.18.0-2-g9a7f627 gcr.io/k8s-staging-dns`

**Comment by prameshj** [comment]
I am curious if you ran into errors building the node-cache arm image. Was this built after pulling from k/dns master? We are seeing build errors described in https://github.com/kubernetes/dns/issues/466

**Comment by SuperQ** [comment]
The check script fails because it's trying to use the docker manifest image, which doesn't get built locally.

I modified the script to add `-amd64` to the images.

I'm getting some startup crashes.

```
$ ./image-checks.sh 1.18.0-2-g9a7f627 gcr.io/k8s-staging-dns
Verifying that iptables exists in node-cache image
iptables v1.8.5 (legacy): no command specified
Try `iptables -h' or 'iptables --help' for more information.
Verifying that node-cache binary exists in node-cache image
2021/06/28 22:21:24 [INFO] Starting node-cache image: 1.18.0-2-g9a7f627
2021/06/28 22:21:24 [FATAL] Error parsing flags - invalid localip specified - "", Exiting
Verifying dnsmasq-nanny startup
I0628 22:21:24.975978       1 main.go:78] opts: {{/usr/sbin/dnsmasq [] false} /etc/k8s/dns/dnsmasq-nanny 10000000000 127.0.0.1:10053}
I0628 22:21:24.976188       1 nanny.go:124] Starting dnsmasq []
W0628 22:21:24.981654       1 nanny.go:150] Got EOF from stdout
W0628 22:21:24.981697       1 nanny.go:150] Got EOF from stderr
F0628 22:21:24.981764       1 nanny.go:220] dnsmasq exited: <nil>
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000182001, 0xc0001ea1c0, 0x42, 0xdb)
	/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1021 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x1c9bbe0, 0xc000000003, 0x0, 0x0, 0xc0004522a0, 0x171aa76, 0x8, 0xdc, 0x0)
	/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:970 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x1c9bbe0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x136de65, 0x12, 0xc00003a1f0, 0x1, ...)
	/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:751 +0x191
k8s.io/klog/v2.Fatalf(...)
	/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1509
k8s.io/dns/pkg/dnsmasq.RunNanny(0x14dc668, 0xc000403410, 0x136c645, 0x11, 0x1ccacf0, 0x0, 0x0, 0x0, 0x136a634, 0xf)
	/go/src/k8s.io/dns/pkg/dnsmasq/nanny.go:220 +0x8b5
main.main()
	/go/src/k8s.io/dns/cmd/dnsmasq-nanny/main.go:82 +0x285

goroutine 18 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x1c9bbe0)
	/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
	/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0xdf

goroutine 22 [chan receive]:
k8s.io/dns/pkg/dns/config.(*kubeSync).Periodic.func1(0xc000403410)
	/go/src/k8s.io/dns/pkg/dns/config/sync.go:84 +0x6f
created by k8s.io/dns/pkg/dns/config.(*kubeSync).Periodic
	/go/src/k8s.io/dns/pkg/dns/config/sync.go:81 +0x3f

goroutine 23 [chan receive]:
k8s.io/dns/pkg/dns/config.(*kubeFileSyncSource).Periodic.func1(0xc0004033e0)
	/go/src/k8s.io/dns/pkg/dns/config/sync_dir.go:71 +0x89
created by k8s.io/dns/pkg/dns/config.(*kubeFileSyncSource).Periodic
	/go/src/k8s.io/dns/pkg/dns/config/sync_dir.go:63 +0x3f
```

**Comment by prameshj** [comment]
@SuperQ the crashes are expected. The test is quite rudimentary, it just ensures that the binaries can be found and can start. I would like to get one more version with vuln fixes in and pick up your PR in a follow up. Will approve this once the tag with vuln fixes is cut.

**Comment by Shahard2** [comment]
Any updates?
Waiting for it to be merged ASAP please...
@SuperQ

**Comment by SuperQ** [comment]
Thanks!

**Comment by Shahard2** [comment]
Thanks alot!

so it already exists in this image?

602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/coredns:v1.8.3-eksbuild.1

**Comment by Shahard2** [comment]
Any update? 
We need it urgently :)
@SuperQ

**Comment by prameshj** [comment]
A 1.20.0 tag has just been cut. The image will be promoted in a day.  It will be at k8s.gcr.io/dns/k8s-dns-node-cache:1.20.0

**Comment by Shahard2** [comment]
Thanks @prameshj how do i make this update in eks ?

**Comment by rtheis** [comment]
There is an important functional regression in CoreDNS version 1.8.3 (see https://github.com/coredns/coredns/issues/4594).  I'm not sure if the bug would impact DNS node cache's usage of CoreDNS but it may be best to bump CoreDNS to version 1.8.4 to be safe.

**Comment by SuperQ** [comment]
@rtheis I was starting to work on trying to upgrade CoreDNS to 1.8.4, but the Go module dependency graph is very complicated.

**Comment by chrisohaver** [comment]
@rtheis, coredns/coredns#4594 affected the kubernetes plugin, which is not used in node cache instances. Node cache instances of coredns forward cluster domain queries to the Cluster DNS deployment of CoreDNS, which does use the kubernetes plugin, and therefore should be at 1.8.4.  But the node cache instances themselves would not be affected by that bug.

**Comment by Shahard2** [comment]
So when 1.8.4 will be released? Anyone knows?

**Comment by prameshj** [comment]
Thanks @chrisohaver. @Shahard2 can you open an issue if you are looking for coredns 1.8.4 support in nodelocaldns for a specific reason?

**Pull request merged**
