### PR TITLE
Update Godeps to client-go 3

### LINKED ISSUE #35: kube-dns should use versioned client-go
kube-dns should use a versioned copy of the client-go repository, rather than HEAD

### PR DESCRIPTION
**Pull request by cmluciano**
These commits now track the release-3 branch of
client-go. The code changes are mostly related to
swapping client-go functions with apimachinery.

Closes #35

### CODE REVIEW

**Comment by bowei** [comment]
Is it possible to split into two patches, one with the actual changes, the other with just vendor/

**Comment by cmluciano** [comment]
Yes, I think a few dependencies were also missed as noted in #48

**Comment by cmluciano** [comment]
Ok I separated this PR into 3 commits. Note that commit https://github.com/kubernetes/dns/pull/90/commits/639bd1868b6a9123f92672e2a2fcbd75e0d27440 may not pass on its own since it cannot properly compile w/o the updated vendors.

**Comment by cmluciano** [comment]
@bowei The build errors relate to the problems I had in #48 . These two dependencies do not seem to be properly vendored. I'm not sure if this is a Godep error or if it's something that I explicitly did during the save step.

**Comment by bowei** [comment]
let me take a look

**Comment by cmluciano** [comment]
@bowei Have you been able to replicate this?

**Comment by bowei** [comment]
Give me a few days (1.7 release...)

**Comment by bowei** [comment]
After fixing the missing packages (onsi/ginkgo), I found that some of the interfaces (cache.Controller) went from struct to interface? Also, the validation package has moved to apimachinery...

**Comment by cmluciano** [comment]
thanks, trying again

**Comment by cmluciano** [comment]
This is still WIP, just testing some stuff

**Comment by cmluciano** [comment]
@bowei @freehan Ok I think this is good to review now.

**Comment by bowei** [comment]
Awesome!!

**Pull request merged**
