### PR TITLE
bump coredns version to fix 404 health check errors

### LINKED ISSUE #381: TIME-WAIT connections :8080
Hi,

I've noticed relatively high number of connections in a TIME-WAIT state targeting `node-dns` (I believe they're for its health route). It's awkward that the number of `node-dns` connections in this state is greater than all other TIME-WAIT connections we have. Am I analysing it badly? Wondering if this may be a bug. 

```
ss --numeric --tcp state connected

State                  Recv-Q               Send-Q                              Local Address:Port                                Peer Address:Port
TIME-WAIT              0                    0                                   169.254.20.10:48814                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48320                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49524                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48014                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49352                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49334                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48282                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49702                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50000                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49830                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48996                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49938                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49056                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49716                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49870                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49436                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49116                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49982                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:47902                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49642                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48418                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48632                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49290                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49804                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50108                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48888                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50126                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49850                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49786                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49628                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49192                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48718                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49610                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48758                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:47820                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49738                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50066                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49668                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48364                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48226                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48572                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48534                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49158                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49400                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48940                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49254                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50178                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49964                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:47954                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49484                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49316                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50092                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49564                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:47736                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48164                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50038                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49378                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49456                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50154                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48076                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49900                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49586                              169.254.20.10:8080
```

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  generation: 2
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: node-local-dns
    kubernetes.io/cluster-service: "true"
  name: node-local-dns
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: node-local-dns
  template:
    metadata:
      annotations:
        prometheus.io/port: "9253"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        k8s-app: node-local-dns
    spec:
      containers:
      - args:
        - -localip
        - 169.254.20.10,172.20.0.10
        - -conf
        - /etc/Corefile
        - -upstreamsvc
        - kube-dns-upstream
        image: k8s.gcr.io/k8s-dns-node-cache:1.15.13
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            host: 169.254.20.10
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: node-cache
        ports:
        - containerPort: 53
          hostPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          hostPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9253
          hostPort: 9253
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 25m
            memory: 5Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /etc/coredns
          name: config-volume
        - mountPath: /etc/kube-dns
          name: kube-dns-config
      dnsPolicy: Default
      hostNetwork: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: node-local-dns
      serviceAccountName: node-local-dns
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - configMap:
          defaultMode: 420
          name: kube-dns
          optional: true
        name: kube-dns-config
      - configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile.base
          name: node-local-dns
        name: config-volume
  templateGeneration: 2
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
```
`node-dns` running on top of EKS with Kubernetes 1.15.11.

### PR DESCRIPTION
**Pull request by xh4n3**
node-cache is using CoreDNS 1.7.0 which produces 404 health check errors, see #381 
bumping CoreDNS to 1.8.1 should fix it.

### CODE REVIEW

**Comment by dpasiukevich** [comment]
Thanks for the PR!

Let me reevaluate the issue https://github.com/kubernetes/dns/issues/476 to see if we could bump coredns version without any regression. Also I will check if it's better to update to newer coredns (1.9.4 or 1.10.0)

**Comment by dpasiukevich** [comment]
On the first look it appears because of the pinned version for skydns (used by kubedns) we cannot upgrade to CoreDNS to higher version than 1.8.4
Unless skydns repo is forked and the codebase and its dependencies are upgraded. So having coredns 1.9.4 or 1.10.0 is not possible atm.

So let's have coredns 1.8.1 as in this PR. Just let me check the performance tests if it's safe to upgrade and https://github.com/kubernetes/dns/issues/476 is still valid.

**Comment by xh4n3** [comment]
> we cannot upgrade to CoreDNS to higher version than 1.8.4

@dpasiukevich is it because the newer CoreDNS is relying on some vendors which conflict with skydns'?

**Comment by dpasiukevich** [comment]
Yeah, there are some shared transitive dependencies to grpc client. At least I found transitive dependency collision for `google.golang.org/grpc/naming`. Other details are described here https://github.com/kubernetes/dns/issues/505

1. Could I ask you to check if that's possible to upgrade to CoreDNS 1.9.4 or 1.10.0? Maybe I overlooked something and it's possible to do it effortlessly. (as I can see right now - skydns repo has to be forked and its codebase+dependecies updated)
2. Meanwhile I will run scalability tests on this PR to see if there's a cache miss regression https://github.com/kubernetes/dns/issues/476)

**Comment by xh4n3** [comment]
I was trying to pin grpc to v1.29.1 to solve the missing `naming` package issue. But it turns out that since v1.9.1, CoreDNS requires gRPC-Go v1.32.0 or later, see https://github.com/coredns/coredns/blob/v1.9.1/pb/dns_grpc.pb.go#L18-L19
So the conflict is inevitably happening here.

The solution can be:
1. Stick with CoreDNS older then v1.9.1
2. Eliminate the code that using `github.com/coreos/etcd/client` package in the `k8s.io/dns/pkg/dns`, as I found the code are just using the etcd Error types from the vendor.

I'd like to go with the second solution, how do you think? @dpasiukevich

**Comment by dpasiukevich** [comment]
Regarding the
> Eliminate the code that using github.com/coreos/etcd/client package in the k8s.io/dns/pkg/dns, as I found the code are just using the etcd Error types from the vendor.

I checked even if we upgrade the `k8s.io/dns/pkg/dns` to a newer version of etcd client, there's still:
`cmd/kube-dns/app/server` -> `github.com/skynetservices/skydns/server` -> `github.com/coreos/etcd/client`

So we'd have to either fork or fix the dependencies in the skydns package.

The main problem is that `kubernetes/dns` repo hosts 2 binaries (on the high level) - kubedns and nodelocaldns. kubedns is virtually deprecated but its pinned dependencies cause us the trouble to upgrade nodelocaldns dependencies.

I'd suggest in the scope of this PR to just have maximum possible CoreDNS version (would be great if it's possible to build with coredns 1.9.0).

**Comment by dpasiukevich** [comment]
You could also run `make images-clean; make build-amd64; make containers-amd64; make test` locally to check the build

**Comment by dpasiukevich** [comment]
Hi, I tried to run performance tests and verify there's no scalability regression mentioned in https://github.com/kubernetes/dns/issues/476 but couldn't find time before going on vac for 2 weeks.

I've asked my teammates to take a look if there's capacity or I will check it when I return.

**Comment by dpasiukevich** [comment]
I imported skydns, upgarded its dependences, which allowed to upgrade to the latest coredns 1.10.0 in https://github.com/kubernetes/dns/pull/551

**Pull request closed without merging**
