### PR TITLE
Adding s390x support

### PR DESCRIPTION
**Pull request by ryan-ibm**
Adding s390x support

### CODE REVIEW

**Comment by bowei** [comment]
@ryan-ibm  -- look like the travis integration failed?

**Comment by ryan-ibm** [comment]
@bowei i fixed the typo. Now the travis build is passing

**Comment by bowei** [comment]
@ryan-ibm -- LGTM, but can you squash the commits into one commit and rebase onto HEAD?

**Comment by ryan-ibm** [comment]
@bowei Moved all commit from me into single commit

**Comment by gajju26** [comment]
@bowei  Raised a PR (https://github.com/kubernetes/dns/pull/56 ) for s390x build

**Pull request merged**
