### PR TITLE
Bump coredns and kubernetes dependencies

### PR DESCRIPTION
**Pull request by dereknola**
## Background
These two dependencies are very Out of Date and are introducing CVEs into downstream repos.
A previous PR was auto opened by dependabot, but never went anywhere. https://github.com/kubernetes/dns/pull/641
This PRs scope is more limited.

## Changes
- Bump coredns to 1.11.3 (latest version)
- Bump K8s to 1.28.14 (the oldest version still being supported as of October 2024). This should ensure maximum compatibility.
- Migrate from deprecated clock package to replacement (clocks and clocks/testing got split up)

The `go mod vendor` has been isolated to a separate commit to make review easier.

### CODE REVIEW

**Comment by dereknola** [comment]
@DamianSawicki Can I get a review on this please? I'm not sure who else to ping, as there hasn't been much activity in this repo in about 4 months.

Related, does this repo need more maintainers?

**Comment by DamianSawicki** [comment]
Hi @dereknola, I think this repo desperately needs more maintainers. Currently no PR can be submitted (at least normally) because CI is broken (so there is little sense in reviewing your PR before resolving this). If you have the capacity to look at https://github.com/kubernetes/dns/issues/646, it would be really great.

**Comment by dereknola** [comment]
@DamianSawicki I've rebased this PR now that the E2E fix is in master.

**Comment by dereknola** [comment]
Looks like the [5s timeout ](https://github.com/kubernetes/dns/blob/master/test/e2e/kubedns/kubedns.go#L54) I added in the last PR is still not quite enough to prevent flaky e2e tests. Might consider bumping it to 10s.

**Comment by dereknola** [comment]
@kl52752 Could you review this please? I will squash these commits, I just was waiting for review readability.

**Comment by DamianSawicki** [comment]
I'm also happy to review it but won't have time this week.

**Comment by dereknola** [comment]
@DamianSawicki any chance you will have time this week to review this PR? I would love to pull this in to RKE2 November patches.

**Comment by DamianSawicki** [comment]
Apologies for the delay. It all looks good.

/lgtm

**Comment by dereknola** [comment]
@kl52752 any chance of getting this approved/reviewed?

**Review by VestigeJ — APPROVED** [review]

**Comment by dereknola** [comment]
Can we get a new release tagged now that this PR is merged?

**Comment by DamianSawicki** [comment]
Sure, I'll take care of it, hopefully tomorrow.

**Comment by Michcioperz** [comment]
@DamianSawicki or whoever will be tagging a release: please note that coredns v1.11 renamed prometheus metrics https://github.com/coredns/coredns/blob/v1.11.0/plugin/forward/README.md#metrics with very little fanfare in release notes https://github.com/coredns/coredns/blob/v1.11.0/notes/coredns-1.11.0.md ("Some changes to forward plugin metrics.") and I believe this should be mentioned more.

**Comment by anokun7** [comment]
How can I tell which version will have this update?

**Comment by kl52752** [comment]
> How can I tell which version will have this update?

new version has not be released yet.

**Comment by DamianSawicki** [comment]
@anokun7 There is a new version https://github.com/kubernetes/dns/releases/tag/1.24.0 ready and in fact already https://github.com/kubernetes/dns/releases/tag/1.24.1 is being prepared.

**Comment by anokun7** [comment]
Thank you for the update @DamianSawicki !

**Pull request merged**
