### PR TITLE
Fix race condition in reverseRecordMap access

### PR DESCRIPTION
**Pull request by MrHohn**
Fix kubernetes/kubernetes#44711.

We don't have a explicit lock for `reverseRecordMap`, all the R/Ws are protected through `cacheLock`, so I followed the same pattern.

@bowei 
cc @etiennetremel

### CODE REVIEW

**Comment by bowei** [comment]
Good catch, I thought I fixed all of these. Can you do a brief scan to see that the all reads hold the lock?

**Comment by MrHohn** [comment]
Did a quick check, two possible concurrent reads in https://github.com/kubernetes/dns/blob/master/pkg/dns/dns.go#L714 and https://github.com/kubernetes/dns/blob/master/pkg/dns/dns.go#L724.

**Comment by MrHohn** [comment]
Updated PR, PTAL

**Comment by weiwei04** [comment]
Encounter this problem, looking forward to see this pr be merged.

**Pull request merged**
