### PR TITLE
DNS Spec: Headless service with no ready endpoints 

### PR DESCRIPTION
**Pull request by chrisohaver**
Proposing that a headless service without any ready endpoints should return `NXDOMAIN`, to match current behavior of kube-dns and CoreDNS.

I'm proposing we update the spec to match the implementation of kube-dns, because the spec was initially based on kube-dns behavior.

If we don't update the spec, then we should open bugs for kube-dns (and CoreDNS) and fix.

see #234

### CODE REVIEW

**Comment by chrisohaver** [comment]
thoughts?

**Comment by johnbelamaric** [comment]
I agree it makes sense to update the spec to match the current behavior. Changing the behavior could have unexpected consequences for users.

**Comment by chrisohaver** [comment]
How can we move this forward.

**Pull request merged**
