### PR TITLE
Upgrade to go 1.18

### PR DESCRIPTION
**Pull request by gcampbell12**
Fixes a number of vulnerabilities in older go versions

### CODE REVIEW

**Comment by dpasiukevich** [comment]
Thanks for the PR!

/lgtm
/approve

**Comment by dpasiukevich** [comment]
a new tag `1.22.11` with this PR is pushed.

Could I ask you to publish the new image to kubernetes/kubernetes as described in https://github.com/kubernetes/dns#release-process steps 7-10?

In case if you won't have enough permissions to download manifest using `parse-image-sha.py`
Images SHA could be taken here:
https://console.cloud.google.com/gcr/images/k8s-staging-dns/global/k8s-dns-kube-dns?mods=logs_tg_prod

Thanks!

**Comment by gcampbell12** [comment]
@dpasiukevich promoting 1.22.11 here - https://github.com/kubernetes/k8s.io/pull/4210

**Pull request merged**
