### PR TITLE
Handle same hostname for multiple pods in a headless service

### PR DESCRIPTION
**Pull request by guillaumerose**
This code improves the handling of headless services pointing at pods sharing
the same hostname.

 + For each hostname, A records should point at the list of pods IPs.
   Currently, only the last pod gets its A record.
 + For the service, a A record should be created for each pod.

Fixes https://github.com/kubernetes/dns/issues/116

cc @dgageot

### CODE REVIEW

**Comment by thockin** [comment]
I know the spec says it should return multiple A records in this case, but I just want to think it through.  Is this the correct behavior?  It's less surprising than dropping all-but-one, though I could argue that using the same hostname twice is a bug on the user's end.

So is the spec wrong or is the code wrong?  If we implement this - what else might break?  Are there apps that actually expect to use DNS as "phantom elimination"?  I feel the current behavior is under-specified to rely on that, but the implementation is reasonably deterministic.  

@bowei @johnbelamaric @smarterclayton @erictune @kubernetes/sig-apps-misc

**Comment by erictune** [comment]
@kow3ns

**Comment by erictune** [comment]
Using the same hostname is not a bug.  

Spreading may be soft rather than hard.  

Someone may want to bring up a size-3 etcd in their 2-node cluster as part of a test.  They don't need HA, they just want to reuse the config.  That should work as similarly as possible to the "normal" case where the pods are properly spread.

**Comment by thockin** [comment]
@erictune I am not clear on your reply.  Let me provide an example and you tell me which behavior is considered correct.

T0: User somehow creates a set of pods that have hostnames "app-1", "app-2", "app-3".  DNS lookups of "service" return 3 distinct A records.  DNS lookups of "app-[123].service" each return one distinct A record.

T1: Some management event happens and, through cut-paste or similar, the app-3 pod is replaced with a new pod that has hostname "app-2".  DNS lookups of "service" return 3 distinct A records.  Question: should a DNS lookup of "app-2" return a single A record (one of the 2 pods, chosen somehow) or should it return 2 A records?

Today it returns 1 record.

**Comment by thockin** [comment]
Another note: if we decide the spec is wrong, and that we should only serve one A record, we have a bug.  When you hit this overlap, the IP of the last pod created "wins".  If that pod goes away, we do not update the PTR to the other pod with the same hostname.

**Comment by erictune** [comment]
Please disregard previous comment.  I was not aware of how the hostname
override behavior affected DNS.

I don't know of any use cases that break either way.  Ken may know some.

**Comment by dgageot** [comment]
Thanks @thockin for the feedback.

When we prepared this PR, we tried real hard to not break existing things and we considered this whole "phantom elimination" couldn't be considered a feature given what's in the spec. But I understand that nonetheless, it *might* be a breaking change.

What do you think we can do to mitigate that risk?

**Comment by johnbelamaric** [comment]
@chrisohaver I believe in CoreDNS we include all IPs. This is consistent with ordinary DNS behavior - it is legal in DNS to have multiple A records with the same name and different IPs.

**Comment by guillaumerose** [comment]
We fixed the CLA check. Any chance to get this merged ? Should we do something ?
Thanks !

**Comment by dgageot** [comment]
ping @thockin

**Comment by guillaumerose** [comment]
Any update on this ?

**Pull request closed without merging**
