### PR TITLE
Add dns-stress-test tool

### PR DESCRIPTION
**Pull request by justinsb**
This performs DNS queries (~100 per second per pod), reporting timing
results to StackDriver.  It demonstrates the significant improvements
attainable with the node-local-dns cache.

### CODE REVIEW

**Comment by axot** [comment]
Hello, I'm running this tool in GKE, when I executed `bazel run //dns:k8s.apply` it said no such target, any ideas?

```
$ bazel run //dns:k8s.apply
ERROR: Skipping '//dns:k8s.apply': no such target '//dns:k8s.apply': target 'k8s.apply' not declared in package 'dns' defined by /home/foobar/dns/tools/dns-stress-test/dns/BUILD.bazel
WARNING: Target pattern parsing failed.
ERROR: no such target '//dns:k8s.apply': target 'k8s.apply' not declared in package 'dns' defined by /home/foobar/dns/tools/dns-stress-test/dns/BUILD.bazel
INFO: Elapsed time: 0.076s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by axot** [comment]
I got `standard_init_linux.go:178: exec user process caused "no such file or directory"` from dns-stress-test pod, so I add a static compile option in `dns/BUILD.bazel`.

```
 42 go_binary(
 43     name = "dns",
 44     embed = [":go_default_library"],
 45     visibility = ["//visibility:public"],
+ 46     static = "on",
 47 )
```

**Comment by MrHohn** [comment]
cc @prameshj

**Comment by bowei** [comment]
@justinsb there is a DNS perf-tests repo https://github.com/kubernetes/perf-tests/tree/master/dns

**Pull request closed without merging**
