### PR TITLE
Fix version on startup

### PR DESCRIPTION
**Pull request by CallMeFoxie**
Hi,
It seems that during startup the kube-dns service is reporting (static) version of kubernetes:
$ make bin/amd64/kube-dns
building : bin/amd64/kube-dns
$ bin/amd64/kube-dns 
I0317 11:24:42.981414   27628 dns.go:49] version: v1.5.2-beta.0+$Format:%h$
...

which is defined in vendor/k8s.io/kubernetes/pkg/version/base.go and seems rather wrong/useless. We should report kube-dns version instead, which is compiled-in during compile time.

After applying this fix:
$ make bin/amd64/kube-dns
building : bin/amd64/kube-dns
$ bin/amd64/kube-dns 
I0317 11:27:32.043009   30292 dns.go:49] version: 1.14.1-dirty

which looks more appropriate.

Have a nice day,
Ashley

### CODE REVIEW

**Comment by CallMeFoxie** [comment]
Forgot to gofmt it, will re-do.

Also need to fix the call to .verflag() as it prints out some odd Kubernetes version rather than Kube-DNS version when called with kube-dns --version.

**Comment by CallMeFoxie** [comment]
Fixed the --version command output as well:

$ docker run doc.ker/<our-stuff>/kubedns-amd64:1.14.1
I0317 12:12:17.558381       1 dns.go:48] version: 1.14.1
F0317 12:12:17.558436       1 server.go:57] Failed to create a kubernetes client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
$ docker run doc.ker/<our-stuff>/kubedns-amd64:1.14.1 --version
Kube-DNS 1.14.1

:)

**Comment by CallMeFoxie** [comment]
not sure why that e2e test failed... any help?

**Comment by bowei** [comment]
looking

**Comment by Scukerman** [comment]
I ran into this issue, can you fix that?

**Comment by CallMeFoxie** [comment]
That was it, forgot to remove the verflag import from sidecar as well :)
Let's see if it e2e tests now. Thanks!

However I have no idea how to update (vendored) Godeps to remove k8s.io/kubernetes/pkg/version/verflag from it :| godep save just errors out on 
godep: no buildable Go source files in /home/ashley/go/src/k8s.io

**Comment by CallMeFoxie** [comment]
Any updates @bowei ?

**Comment by bowei** [comment]
This doesn't look like the right fix. version.go is automatically generated by `build/build.sh`:

```go
go install                                                         \
    -installsuffix "static"                                        \
    -ldflags "-X ${PKG}/pkg/version.VERSION=${VERSION}"            \
    ./...
```

**Comment by CallMeFoxie** [comment]
Check the code -- it was referencing verflag from kubernetes pkg so I copied it to dns itself. It was reporting VERSION from k8s.io/kubernetes/pkg/version

**Comment by bowei** [comment]
ah ok, sorry, taking another look

**Comment by bowei** [comment]
thanks

**Pull request merged**
