### PR TITLE
Revert upgrade to CoreDNS 1.5.0

### PR DESCRIPTION
**Pull request by prameshj**
The new image is not running the node-cache cleanup routine which deletes iptables rules and local interface created for node-cache. This is a problem when disabling the addon, if there is left over state.

Looks like the shutdown callbacks in forward plugin are taking longer/not completing before pod is shut down. The node-cache cleanup would be called after this. 
Reverting the upgrade to get the image into k/k before code freeze.
Created an issue to rootcause this and upgrade to 1.5.0 - https://github.com/kubernetes/dns/issues/306

### CODE REVIEW

**Comment by axot** [comment]
Hello, is any updates for this?

**Comment by prameshj** [comment]
We need atleast prometheus version 0.9.3, but the current skydns code has a constraint on version 0.8.0. I submitted https://github.com/skynetservices/skydns/pull/350 for review, but have not gotten an update. I will modify this repo to use a fork of skydns and modify it there.

**Comment by axot** [comment]
Thank you. How about the bug around `OnProcessExit` callback, it seems not works after `1.5.0`?

**Comment by prameshj** [comment]
> Thank you. How about the bug around `OnProcessExit` callback, it seems not works after `1.5.0`?

I haven't had a chance to debug that. Will do as part of my ongoing change. In the meantime, if you have any insights to share on the cleanup issue, that would be very helpful.

**Comment by axot** [comment]
I did some tries, instead of appending to the tail of `caddy.OnProcessExit`, but insert into the head of the list. It did not work properly, so I'm going to create a simple project to easy debug this issue, at the same time, I found there are some cases that node-local-node totally not working. it may be related to `hostNetwork: true, dnsPolicy: ClusterFirstWithHostNet`, the condition is not clarified, I will fire an issue of this in the next week.

**Pull request merged**
