### PR TITLE
Upgrade to kubernetes 1.21.

### PR DESCRIPTION
**Pull request by prameshj**
This is needed to access the Service.Spec.ClusterIPs field for Dual-Stack clusters.

The changes were created by manually modifying the kubernetes dependencies from 1.19.12 to 1.21.6 in go.mod. and running `go mod vendor`.

This also fixes the vuln mentioned in https://github.com/kubernetes/dns/pull/500

### CODE REVIEW

**Comment by prameshj** [comment]
Checked the images using ./images-check.sh.

```
 ./image-checks.sh 1.21.4-dirty <personal repo>
Verifying that iptables exists in node-cache image

iptables v1.8.5 (legacy): no command specified
Try `iptables -h' or 'iptables --help' for more information.
Verifying that node-cache binary exists in node-cache image
2022/01/24 20:42:50 [INFO] Starting node-cache image: 1.21.4-dirty
2022/01/24 20:42:50 [FATAL] Error parsing flags - invalid localip specified - "", Exiting


Verifying dnsmasq-nanny startup

I0124 20:42:52.757856       1 main.go:78] opts: {{/usr/sbin/dnsmasq [] false} /etc/k8s/dns/dnsmasq-nanny 10000000000 127.0.0.1:10053}
I0124 20:42:52.758003       1 nanny.go:124] Starting dnsmasq []
W0124 20:42:52.779243       1 nanny.go:150] Got EOF from stdout
W0124 20:42:52.779291       1 nanny.go:150] Got EOF from stderr
F0124 20:42:52.779333       1 nanny.go:220] dnsmasq exited: <nil>
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
	/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1026 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x1c81fe0, 0x3, {0x0, 0x0}, 0xc0004045b0, 0x0, {0x15d9e61, 0xc0004007e0}, 0x0, 0x0)
	/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:975 +0x63d
k8s.io/klog/v2.(*loggingT).printf(0x0, 0x394eb0, {0x0, 0x0}, {0x0, 0x0}, {0x11f2f4f, 0x12}, {0xc0004007e0, 0x1, ...})
	/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:753 +0x1e5
k8s.io/klog/v2.Fatalf(...)
	/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1514
k8s.io/dns/pkg/dnsmasq.RunNanny({0x13750c0, 0xc0003fc330}, {{0x11f17a6, 0x11}, {0x1cb2948, 0x0, 0x0}, 0x0}, {0x11ef8de, 0xf})
	/go/src/k8s.io/dns/pkg/dnsmasq/nanny.go:220 +0x7ba
main.main()
	/go/src/k8s.io/dns/cmd/dnsmasq-nanny/main.go:82 +0x2c5


Verifying kube-dns startup

I0124 20:42:55.325006       1 dns.go:47] version: 1.21.4-dirty
F0124 20:42:55.325068       1 server.go:61] Failed to create a kubernetes client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
	/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1026 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x24341a0, 0x3, {0x0, 0x0}, 0xc000295e30, 0x0, {0x1bf515a, 0xc00061efe0}, 0x0, 0x0)
	/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:975 +0x63d
k8s.io/klog/v2.(*loggingT).printf(0x1e, 0x3f, {0x0, 0x0}, {0x0, 0x0}, {0x16cfa6a, 0x28}, {0xc00061efe0, 0x1, ...})
	/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:753 +0x1e5


Verifying sidecar startup


I0124 20:42:57.890825       1 main.go:51] Version v1.21.4-dirty
I0124 20:42:57.890876       1 server.go:46] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
W0124 20:42:57.891192       1 server.go:65] Error getting metrics from dnsmasq: read udp 127.0.0.1:52711->127.0.0.1:53: read: connection refused
W0124 20:43:02.891589       1 server.go:65] Error getting metrics from dnsmasq: read udp 127.0.0.1:49771->127.0.0.1:53: read: connection refused

```

**Comment by prameshj** [comment]
/hold cancel

cc @cezarygerard

**Comment by cezarygerard** [comment]
@bowei @prameshj 
Could you please merge this PR?
Thanks!

**Pull request merged**
