### PR TITLE
fix make file

### PR DESCRIPTION
**Pull request by andyxning**
remove useless build volume mapping when build binaries.

By removing `-v $$(pwd)/bin/$(ARCH):/go/bin`, we can avoid an empty dir  `bin/ARCH/linux_ARCH`.

/cc @bowei

### CODE REVIEW

**Comment by thockin** [comment]
Needed for cross-builds, if I recall.

**Comment by andyxning** [comment]
@thockin After a deep look, you're right. It is mainly used to get none amd64 binaries. 

In order to make the volume mount more clear and maintainable, I suggest we always only mount `/go/bin/linux_ARCH` and use `GOBIN` to effectively workaround the problem to get `amd64` binaries.

**Comment by andyxning** [comment]
@bowei @thockin PTAL.

**Comment by bowei** [comment]
Can you explain in detail what this does change? What is the problem you are trying to solve?

**Comment by andyxning** [comment]
@bowei

As stated in the PR description. For now, there will be an empty `bin/ARCH/linux_ARCH` dir after the `make build`. It is useless, imo. By removing `-v $$(pwd)/bin/$(ARCH):/go/bin`, we can avoid an empty dir `bin/ARCH/linux_ARCH`.

**Comment by bowei** [comment]
That directory is created in bin/ which removed as part of `make clean`. Is this causing a problem with the build?

**Comment by andyxning** [comment]
No. There is no problem in fact. :) 

Just to make the `bin` directory more cleaner.

**Comment by andyxning** [comment]
ping @bowei

**Comment by andyxning** [comment]
cc @bowei

**Comment by bowei** [comment]
ok, lgtm

**Comment by andyxning** [comment]
@bowei Should we merge this PR? :)

**Pull request merged**
