### PR TITLE
Use alpine as base image on all platforms

### PR DESCRIPTION
**Pull request by MrHohn**
Ack https://github.com/kubernetes/contrib/pull/2670#issuecomment-315712954.

@guirish Would you be able to test the s390x image? Thanks.

/assign @bowei 

cc @GheRivero @gajju26

### CODE REVIEW

**Comment by MrHohn** [comment]
@luxas Thanks for taking the look :)

**Comment by thockin** [comment]
@tallclair ptal - you own base img strategy AFAIK

**Comment by guirish** [comment]
@MrHohn sure we will build and test kube-dns using kube-cross image locally, and update you the status. Kindly let us know once you have pushed new kube-dns images on google repository for our reference.

CC: @gajju26

**Comment by tallclair** [comment]
Retroactive LGTM :)

And :+1: for consolidating on alpine now that they support the platforms we need.

**Comment by MrHohn** [comment]
@guirish FYI new kube-dns images were cut: https://github.com/kubernetes/dns/releases

**Comment by guirish** [comment]
Hi @MrHohn,  To verify I pulled the latest Alpine:3.6 image on x86 and s390x/busybox:glibc & s390x/alpine on s390x and I found that now all the images have nobody user associated with nobody group. So nobody user specific issue won't arise now, but yes it would be a good if we have similar BaseImages on all the ARCH's in **_images/dnsmasq/Makefile_** file.

CC: @luxas 

**Specification:**
on x86: User nobody specifications for alpine:3.6 image
**nobody: x:65534:65534:nobody:/:/sbin/nologin**

on s390x: User nobody specifications for s390x/alpine:3.6 image
**nobody: x:65534:65534:nobody:/:/sbin/nologin**

on s390x: User nobody specifications for s390x/busybox:glibc &  s390x/busybox image
**nobody: x:65534:65534:nobody:/home:/bin/false**

**Pull request merged**
