### PR TITLE
update dnsmasq to 2.79

### PR DESCRIPTION
**Pull request by matt-potter**
Specifically this provides min-port at a sane default (1024), which would aid our deployments with kube-aws, where are are unable to pass custom flags to the dnsmasq process

### CODE REVIEW

**Comment by bowei** [comment]
cc: @prameshj

**Comment by prameshj** [comment]
The e2e tests in kubernetes/kubernetes need to be fixed before upgrading to dnsmasq 2.79
https://github.com/kubernetes/kubernetes/issues/69123

**Comment by bowei** [comment]
@prameshj is this still relevant?

**Comment by prameshj** [comment]
/remove-lifecycle rotten
/ok-to-test

The kubernetes e2e tests have been fixed.
@matt-potter Do we still need this change?

**Pull request closed without merging**
