### PR TITLE
Fix error string should not be capitalized and sort import

### PR DESCRIPTION
**Pull request by yuzhiquan**
- error string should not be capitalized
-  sort import

### CODE REVIEW

**Comment by prameshj** [comment]
Change looks good.. but travis failed due to rate limiting - https://travis-ci.org/github/kubernetes/dns/builds/751919470

Can you rename the commit or make some change to trigger this again? I can lgtm after that.

**Comment by yuzhiquan** [comment]
@prameshj Sure, and build succ now https://travis-ci.org/github/kubernetes/dns/builds/752065531

**Comment by prameshj** [comment]
/lgtm
thanks!

**Pull request merged**
