### PR TITLE
Install ginkgo as part of travis install step.

### PR DESCRIPTION
**Pull request by prameshj**
Remove logic to build the binary.

Used the config documented in http://onsi.github.io/ginkgo/#ginkgo-and-continuous-integration

### CODE REVIEW

**Comment by prameshj** [comment]
https://travis-ci.org/github/kubernetes/dns/builds/733369854

This is failing travis build.

/hold

**Comment by MrHohn** [comment]
> ../../onsi/ginkgo/ginkgo/generate_command.go:244:9: undefined: strings.ReplaceAll
The command "go get -v github.com/onsi/ginkgo/ginkgo" failed and exited with 2 during .

Looks like ReplaceAll was only added in Go 1.12+.

**Comment by prameshj** [comment]
> > ../../onsi/ginkgo/ginkgo/generate_command.go:244:9: undefined: strings.ReplaceAll
> > The command "go get -v github.com/onsi/ginkgo/ginkgo" failed and exited with 2 during .
> 
> Looks like ReplaceAll was only added in Go 1.12+.

Yup, changing travis to use 1.12.

**Comment by prameshj** [comment]
Opened https://github.com/onsi/ginkgo/issues/727 to get recommendations on how to get this working.

**Comment by prameshj** [comment]
Closing this, Already did this in https://github.com/kubernetes/dns/pull/413/commits/80f2936eda5d0d57bb3c4dcd898bfc2b61cca307

**Pull request closed without merging**
